### PR TITLE
Update the Klipper Beginner's Macro Guide

### PR DESCRIPTION
**Pull request by voidtrance**
This commit contains mostly formatting changes that makes it easier for me to maintain and update the document.

However, there are some content updates as well:
  - Expand the "Variables" section with an example.
  - Add a new section - User Macro Settings - detailed how macros can be used to store "global" variables.
  - Some workding/grammer fixes.

### CODE REVIEW

**Review by shiftingtech — CHANGES_REQUESTED** [review]
I don't believe just the docs has gcode as one of the code block styles it recognises

**Comment by voidtrance** [comment]
> I don't believe just the docs has gcode as one of the code block styles it recognises

Is that an issue? Are you saying that you want me to remove the style?

**Comment by northrup** [comment]
This type of highlighting is valid for Just The Docs.

Just The Docs leverages Jekyll and Jekyll includes the `Rouge` ruby syntax highlighter. No syntax is being being highlighted here, but it'll parse all the same. 

Here's also the docs from Just The Docs for reference https://just-the-docs.github.io/just-the-docs/docs/ui-components/code/

**Comment by shiftingtech** [comment]
The original submission did have a "gcode" syntax selected.

It's my direct observation that when people have set the syntax
highlighting to "gcode" in the past, it has resulted in broken webpages,
when the site is rendered out through github pages.

It may be a bug in just the docs, or something more github related, I don't
know, but it seems to cause bad things to  happen.  Do you have any
specific information on how to avoid that, without resorting to my crude
solution of "don't use that highlighter"?

**Comment by northrup** [comment]
> It's my direct observation that when people have set the syntax highlighting to "gcode" in the past, it has resulted in broken webpages, when the site is rendered out through github pages.

@shiftingtech 🤦 that totally makes sense, and I missed that as I didn't look at the commit history on this PR. [Rouge](https://github.com/rouge-ruby/rouge/tree/master) doesn't have support for `gcode` and so it would error or fail to render.

As this PR stands now, the code blocks will render as generic code blocks with no highlighting, which while less colorful, I think is still probably useful for documentation.

**Comment by voidtrance** [comment]
Is there any more work required on my end for this PR?

**Comment by northrup** [comment]
@voidtrance I personally don't think so. I think your current PR as stands is correct now and ready to be reviewed for merge.

**Review by shiftingtech — APPROVED** [review]

**Pull request merged**
