### PR TITLE
Add "How to install on SSD" + Changes to "Installing Mainsail and Fluidd"

### PR DESCRIPTION
**Pull request by T4KUUY4**
Added a little guide for installing on SSD. 
More Reliable and doesn't die as fast. 
Also allows for larger gcodes or timelapse videos.

### CODE REVIEW

**Comment by T4KUUY4** [comment]
Added default username and password for Pi

**Comment by T4KUUY4** [comment]
> Could you break this up a bit? The edits to the Fluidd & Mainsail guides seem good, more or less as-is. But the ssd guide seems like a separate community doc to me, simply because it's a fairly significant deviation from the stock build.

sure. ill move it to the community how-to´s

**Comment by T4KUUY4** [comment]
@shiftingtech Better now?

**Comment by shiftingtech** [comment]
Yep, looks good now, thanks.

**Pull request merged**
