### PR TITLE
Typographic, compliance and markdown fixes, adding WinSCP section, Improving the formatting of some sections

### PR DESCRIPTION
**Pull request by HumbleDeer**
- Formatting, typographic and compliance fixes
- Add OrcaSlicer as possible slicer (as it's popular nowadays and a fork of PrusaSlicer)
- Add parents and grandparents to the Electronics pages
- Dupe controller wiring list into separate file
- Explicit toc assignment
- Re-order Mini12864 checklist wording
- Optimize large images
- Add the WinSCP section to the SSH guide
- Added a favicon (wasn't a thing yet apparently)

[Markdown compliance & Formatting improvements](https://github.com/VoronDesign/Voron-Documentation/commit/80b0bae3868279d6072767efb7fa06f7e62aee4d) 

[Mini12864 & MCU's improvements](https://github.com/VoronDesign/Voron-Documentation/commit/f51e9a2e96d912591e3bd385c8ec673347dbbbac) 

[Add the SCP section](https://github.com/VoronDesign/Voron-Documentation/commit/adcf11f14afae3b19e6356fa3918816c6ca12c37)

### CODE REVIEW

**Comment by shiftingtech** [comment]
Your edits are accompanied by a lot of extraneous whitespace changes. Looks like you changed the carriage return format of the files you edited.  Can you fix that up, so your diffs are a little cleaner please?

**Comment by HumbleDeer** [comment]
The whitespace changes are probably intentional, depending on exactly which ones you mean. There were lots of extraneous whitespace characters that break Markdown formatting rules. There's rules on when, where, and how many. :)

**Comment by shiftingtech** [comment]
No, in fact, that is not what I mean.  I mean that files before you touched them are using unix line endings (LR only).  After your edits, the files have mysteriously been reformatted using Windows style line endings  (CRLR). 

```
$ file sw_miniE3_v20_wiring.md 
sw_miniE3_v20_wiring.md: ASCII text
```
vs
```
$ file sw_miniE3_v20_wiring.md 
sw_miniE3_v20_wiring.md: ASCII text, with CRLF line terminators
```
for example.

**Comment by HumbleDeer** [comment]
Oh, I see! Let me check that again then. This may have been an error in the configuration of my text editor.

**Review by shiftingtech — APPROVED** [review]

**Pull request merged**
