### PR TITLE
GitHub Backup: Update repository instructions

### PR DESCRIPTION
**Pull request by mjonuschat**
Update the instructions to make the initial repository creation a smoother experience:

- Force `git` to use `main` as the branch name
- Ensure the new repository on GitHub is empty to allow successful initial pushes

### CODE REVIEW

**Comment by FHeilmann** [comment]
This looks like a duplicate of #393 . Maybe you could combine your efforts and put them into one of the two prs?

**Comment by hartk1213** [comment]
Yeah was just going to comment the same ..looks like a dupe of #393

**Comment by mjonuschat** [comment]
The first commit was made redundant by Eric's changes, the second commit is still valid. I'll rebase on top of #393

**Comment by EricZimmerman** [comment]
this one has a few more things about NOT creating license file etc. mjonschat and i spoke on discord and i had some time today to do some of the changes, but this is the rest. Specifically

https://github.com/VoronDesign/Voron-Documentation/pull/394/commits/6beee7a4db2af2c0ea8401a007ef85d6c9f01960

**Comment by hartk1213** [comment]
Ok sounds good 👍🏻

**Review by hartk1213 — APPROVED** [review]

**Pull request merged**
