### PR TITLE
Octopus: Enable PE5 as a precaution

### PR DESCRIPTION
**Pull request by top-gun**
Setting PE5 to high makes sure the hotend fan is running to avoid heat-creep. The fan is turned off automatically once Klippy has started on the pi and communicates with the MCU. There is a matching PR in the Voron-2 repo to ensure the same thing in case of a MCU shutdown.

### CODE REVIEW

**Comment by cbc02009** [comment]
If we were going to make this change (and it's not a bad idea) we'd want to do it for all the printers and boards, not just v2 with octopus.

**Comment by clee** [comment]
@top-gun Are you willing to update the rest of the stock configs to apply this change to them?

**Comment by top-gun** [comment]
I can and will add that for the entire range if the maintainers feel the change is worth to be included. It's a few hours of effort to make this for all the supported boards, so with all due respect, may I ask beforehand if this change is wanted?

I ran into the same situation on the Klipper config files - I filed a change, responded to the request that it should be done for all boards, and later it was decided that it's an issue which should be handled in the Klipper code, not in the config. That's why I ask.

**Comment by clee** [comment]
Sounds like @cbc02009 is on board, and I agree, I think this is a worthwhile change, but we want to ensure that these things are consistent in our documentation and our example configurations so that people don't get different behavior based on which MCU they build their Voron with.

I can't speak for the rest of the maintainers since I'm the new guy on the team, but I'd be happy to merge this once it covers all the current MCUs we document.

**Comment by top-gun** [comment]
Fair enough, I will squeeze this into the weekend. :)

**Comment by top-gun** [comment]
Ok, I think I have them all covered - except BTT Mini E3 V1.2 because it doesn't have a controlled hotend fan. That fan is always on anyway.

**Comment by eddietheengineer** [comment]
Hello @top-gun! I appreciate your effort here, it looks like you've gone through quite a bit of work on configs. 

I will admit I'm a bit uneasy about having users define a pin as "high" on startup, from a few different perspectives. 

First off, I will admit some of that is due to a recent issue where I was trying out something new and fat fingered a "PA3" instead of "PB3" and my Spider was unresponsive after I flashed it. Luckily in that case I was able to flash the boot loader again in DFU mode, but for a board where that isn't possible it could mean bricking the board and needing to buy an STLink or other device to recover it. This also could mean by accident typing the wrong pin and forcing the hotend heater or bed full on.

The other case would be where the pin is properly set, but someone is using a slightly variant configuration without realizing what the forced pin on startup is, and by accident plugs say an SSR or other device into that fan port. This would also cause a thermal runaway--hopefully the user would have a thermal fuse, but my best guess is that that's probably 50% or less of the population. 

As a high level, I see it:
Plus sides to the change: running the hotend fan for the ~5-10 seconds when Klipper is starting up, which may in some cases help prevent a clog
Minus sides: extra complexity for users, possibility of creating an unsafe condition or causing a board issue that may be difficult to fix.

I'm not saying yes or no, just trying to provide some thoughts or perspective, I'm curious to see what you all think!

**Comment by top-gun** [comment]
Hi Eddie,

thank you for your feedback on this. I would like to add another scenario for review, because you said "5-10s" after restart.

Imagine you are standing at the printer, and notice some mishap, like a microswitch not triggering or a head crash. You press the reset button on the 12864, it's a reasonable first step to get out of the issue. The mcu will reset, Klipper will shut down.

The machine will not recover until you issue a firmware restart or power-cycle the printer. This can easily take a minute, and in that time, your hotend is clogged. Dragons are popular on Vorons, and they don't take that condition well.

**Comment by top-gun** [comment]
Reading through the recent changes, this PR seems no longer consistent with the current state of the board documentation, and the discussion ran out of steam.

**Pull request closed without merging**
