### PR TITLE
Fix link in build/slicer/first_print.md

### LINKED ISSUE #279: Fix Link ....
.... on 
https://docs.vorondesign.com/build/slicer/first_print.html

first link is wrong

### PR DESCRIPTION
**Pull request by philippbeckmann**
The link to the test print folder is invalid. 
Fixes  #279

### CODE REVIEW

**Comment by clee** [comment]
Good catch! Thanks for the fix.

**Comment by timmit99** [comment]
@clee  should this now point to Voron extras repository instead of the 2.4 folder?

https://github.com/VoronDesign/Voron-Extras/tree/main/Test_Prints

**Comment by clee** [comment]
> @clee  should this now point to Voron extras repository instead of the 2.4 folder?
> 
> 
> 
> https://github.com/VoronDesign/Voron-Extras/tree/main/Test_Prints

Well, if I had known that this repo existed… yeah, that seems like a better link target! I'll update it.

**Comment by GadgetAngel** [comment]
This link `` Download the “voron\_design\_cube\_v7.stl” from the [Voron Github page](https://github.com/VoronDesign/Voron-2/tree/Voron2.4/STLs/Test_Prints)``  now does not work on the LIVE website:
image

When I press the "Voron Github page" link I now get the following:
image

Please update to: 
```
Download the “voron\_design\_cube\_v7.stl” from the [Voron Github page](https://github.com/VoronDesign/Voron-Extras/tree/main/Test_Prints), and open the file in your chosen slicer. Use the default slicer settings, but make sure the hotend temperature and bed temperature are correct for the filament you are using. A good starting point is 240C hotend temperature, 100C heated bed temperature, and 92% flow for ABS.
```

**Comment by philippbeckmann** [comment]
The change has not yet been rolled out to the live website.

**Comment by GadgetAngel** [comment]
> The change has not yet been rolled out to the live website.

Yeah, I just realized that, sorry

**Comment by gonium** [comment]
Still not live, I saw this PR while preparing my own for this issue ;-)

**Pull request merged**
