### PR TITLE
Typo fixes for community howto docs

### PR DESCRIPTION
**Pull request by clee**
There are a lot of changes here. I'd like to get signoff from everybody whose files I touched before this goes in.

### CODE REVIEW

**Comment by bdbell** [comment]
@clee I think all of this is generally fine, can you get sign-off from the folks you are editing?

**Comment by clee** [comment]
I don't appear to have the ability to set reviewers, but:
@Drachenkaetzchen has signed off on Discord, but a :+1: here would be good
@T4KUUY4, same for you

@alchemyEngine, @thiagolocatelli, @sorvis, please take a look and give a :+1: or :-1:

**Comment by thiagolocatelli** [comment]
👍🏽

**Comment by alchemyEngine** [comment]
@clee 👍

**Comment by T4KUUY4** [comment]
👍

**Comment by Drachenkaetzchen** [comment]
👍

**Comment by sorvis** [comment]
:+1:

**Pull request merged**
