### PR TITLE
Update V1_gantry_wires.md

### PR DESCRIPTION
**Pull request by jltx1**
add wire lengths, correct chains

### CODE REVIEW

**Comment by dubjay2k** [comment]
Chain length seems to be a bit short here.  As another data point, my 300 build has a X chain that is roughly 430mm and a Y chain of 480mm.  There is no Z chain in the BOM spec.

**Comment by jltx1** [comment]
so thats minimum 910mm, plus connecting between and down to electronics enclosure.  I'm saying 1650mm.  Why too short?
All X wires go through both chains and there are no wires unique to Y chain so I listed all under X.

Z chain is just wire bundle from bed to enclosure.  Not typically in a chain but could be.  Just letting people know how much wire to expect there.

**Comment by dubjay2k** [comment]
@jltx1 I was under the impression that was the length of the chain - and you had it as mm rather than cm.  

I'm thinking since there's only 1 wire bundle on a V1, vs. 3 separate ones on a V2, we probably don't need to actually to break it out by x/y/z.  Maybe call it Toolhead > Controller and Bed > Controller for clarity?  

And I don't know if it's better to be safe than sorry in the case where somebody ends up cutting their wires a bit short.  Perhaps a note stating that this number is an absolute minimum and the builder may want to add some extra at their own discretion to allow for different wiring paths?  I could have sworn the last time I ran a new wire from the toolhead, it was closer to 2m, but it terminated close to where the controller fan is situated in the backpack.

**Comment by jltx1** [comment]
I was told just to fill in the missing information.  But I'm all for less confusion in the documentation and agree removing the chain references is better.  I don't know who has the authority on such decisions.

I used 165cm and I will likely trim down most wires, so it is not the absolute minimum.  In fact I think it is a good recommended length, but worth a note saying one could add margin.  I think 2m would be too much and awkward to organize in that bay.

**Comment by bdbell** [comment]
Closing as the change was incorporated with some other reformatting into PR #84.

**Pull request closed without merging**
