### PR TITLE
Add instructions for MKS Monster8

### PR DESCRIPTION
**Pull request by RealDeuce**

### CODE REVIEW

**Comment by shiftingtech** [comment]
I can't find anybody on the Dev team who has this board, so we can't really test it out.
Could you submit it to the Community section please?  I think it would make sense to put it under "Alternate Electronics", though I know that section is non-mcu stuff at the moment.

**Comment by RealDeuce** [comment]
Is the dev team interested in one to verify it?  Makerbase has offered to send the dev team a board for free before, but nobody seemed interested.

**Comment by bdbell** [comment]
> Is the dev team interested in one to verify it?  Makerbase has offered to send the dev team a board for free before, but nobody seemed interested.

I would be willing to test it.

**Comment by makerbase-mks** [comment]
@bdbell Thank you . Please provide your post information, I will send the board to you. Here is my email: mensonlms2016@gmail.com

**Pull request merged**
