### PR TITLE
Update Fluidd Installation Instructions

### LINKED ISSUE #327: Fluiddpi is no longer maintained
Docs suggested use of FluiddPi but FluiddPi states:

WARNING: FluiddPI is not under active maintenance and we've had reports of users finding issues while using it. As such, our recommendation is that you do not use FluiddPI, and instead use KIAUH to install Fluidd.

Suggest the docs be changed in favor of Kiauh.

### PR DESCRIPTION
**Pull request by northrup**
The docs on the FluiddPI site state that it is no longer being maintained and they recommend using KIAUH for installation.
This PR is an attempt to capture that.

closes #327

### CODE REVIEW

**Comment by northrup** [comment]
Tagging @nemgrea for commentary or approval 🙇

**Comment by daniel-sousa-me** [comment]
This has been stale for some time. I think this is relatively urgent because most new Voron users may not be familiar with the Raspberry Pi + GNU/Linux ecosystem and may be overwhelmed by having 2 sets of conflicting instructions.

**Comment by northrup** [comment]
@daniel-sousa-me i agree. I'm not sure how to draw more attention to it.

**Comment by daniel-sousa-me** [comment]
I was looking again at the software installation pages and I was thinking that instead of having 3 separate instructions for each UI, it could just recommend kiauh.

I've only started using it recently, but it seems really solid.

**Comment by northrup** [comment]
@daniel-sousa-me I had thought about that, but didn't suggest that as I think there would be people that didn't want use the package install script, however the Fluidd developers tell you themselves to use KIAUH to install their front end.

**Review by shiftingtech — APPROVED** [review]
I don't love this guide, in so far as I don't really like the kiauh instructions.  But, you're right.  we do need to get rid of the fluiddpi instructions, so...sold.

**Comment by northrup** [comment]
@shiftingtech I don't disagree. I'll see if I can't suggest some edits to their directions.

**Pull request merged**
